//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btlMVC01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class LOAISANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAISANPHAM()
        {
            this.SANPHAM = new HashSet<SANPHAM>();
        }
        [DisplayName("Mã loại sản phẩm")]
        public string maloaisp { get; set; }
        [DisplayName("Tên loại sản phẩm")]
        public string tenloaisp { get; set; }
        [DisplayName("Mô tả sản phẩm")]
        public string mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAM { get; set; }
    }
}
