//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btlMVC01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class NHANVIEN
    {
        [DisplayName("ID người dùng")]
        public string manv { get; set; }
        [DisplayName("Tên người dùng")]
        public string tennv { get; set; }
        [DisplayName("Tên đăng nhập")]
        public string tendangnhap { get; set; }
        [DisplayName("Mật khẩu")]
        public string matkhau { get; set; }
        public string maloainv { get; set; }
    
        public virtual LOAINHANVIEN LOAINHANVIEN { get; set; }
    }
}
