//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btlMVC01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SANPHAM
    {
        public string masp { get; set; }
        [DisplayName("Tên sản phẩm")]
        public string tensp { get; set; }
        [DisplayName("Mo tả")]
        public string Mota { get; set; }
        public string hinhanh { get; set; }
        public Nullable<int> gia { get; set; }
        public Nullable<int> soluong { get; set; }
        public string maloaisp { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
